export const RECIPE_CATEGORIES = {
  0: "Breakfast",
  1: "Lunch",
  2: "Dinner",
  3: "Snack",
  4: "Dessert",
  5: "Appetizer",
  6: "Soup",
  7: "Salad",
  8: "Main Course",
  9: "Side Dish",
  10: "Beverage",
  11: "Smoothie",
  12: "Bread",
  13: "Pasta",
  14: "Rice",
  15: "Meat",
  16: "Fish",
  17: "Vegetarian",
  18: "Vegan",
  19: "Gluten Free",
  20: "Low Carb",
  21: "High Protein",
  22: "Quick Meal",
  23: "Slow Cooker",
  24: "Other"
} as const;

export const RECIPE_CATEGORIES_ARRAY = [
  { value: '', label: 'All Categories' },
  { value: 0, label: 'Breakfast' },
  { value: 1, label: 'Lunch' },
  { value: 2, label: 'Dinner' },
  { value: 3, label: 'Snack' },
  { value: 4, label: 'Dessert' },
  { value: 5, label: 'Appetizer' },
  { value: 6, label: 'Soup' },
  { value: 7, label: 'Salad' },
  { value: 8, label: 'Main Course' },
  { value: 9, label: 'Side Dish' },
  { value: 10, label: 'Beverage' },
  { value: 11, label: 'Smoothie' },
  { value: 12, label: 'Bread' },
  { value: 13, label: 'Pasta' },
  { value: 14, label: 'Rice' },
  { value: 15, label: 'Meat' },
  { value: 16, label: 'Fish' },
  { value: 17, label: 'Vegetarian' },
  { value: 18, label: 'Vegan' },
  { value: 19, label: 'Gluten Free' },
  { value: 20, label: 'Low Carb' },
  { value: 21, label: 'High Protein' },
  { value: 22, label: 'Quick Meal' },
  { value: 23, label: 'Slow Cooker' },
  { value: 24, label: 'Other' }
] as const;

export type RecipeCategoryValue = keyof typeof RECIPE_CATEGORIES;
